### PR TITLE
Update hello.adb

### PR DESCRIPTION
**Pull request by Rijavel**
Wasn't too sure what to add so I put in an introduction to the program.

### CODE REVIEW

**Comment by BKambic** [comment]
How did you set up the branch?

**Comment by Rijavel** [comment]
Pretty sure after I put my addition, I click for the branch

**Review by curzsh — COMMENTED** [review]
trolling cause its just a learning experiment but INDENTATIONNNNNNNNNNN

**Comment by jacksonchen07** [comment]
Yes. Indentations!

**Comment by jacksonchen07** [comment]
Will merge just to go with the work flow

**Pull request merged**
